#!/bin/bash

echo "🚀 MoonFeed Deployment Guide"
echo "=============================="
echo ""

echo "📋 Prerequisites:"
echo "1. GitHub account"
echo "2. Vercel account (connected to GitHub)"
echo "3. Render account"
echo ""

echo "🔧 Steps to Deploy:"
echo ""

echo "1️⃣  Create GitHub Repository:"
echo "   • Go to https://github.com/new"
echo "   • Repository name: moonfeed"
echo "   • Make it public (or private if you prefer)"
echo "   • Don't initialize with README (we already have one)"
echo "   • Click 'Create repository'"
echo ""

echo "2️⃣  Push to GitHub:"
echo "   Run these commands in your terminal:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/moonfeed.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo "3️⃣  Deploy Backend to Render:"
echo "   • Go to https://render.com"
echo "   • Click 'New' → 'Web Service'"
echo "   • Connect your GitHub repository"
echo "   • Select your moonfeed repository"
echo "   • Name: moonfeed-backend"
echo "   • Environment: Node"
echo "   • Build Command: npm install"
echo "   • Start Command: npm start"
echo "   • Root Directory: backend"
echo "   • Plan: Free"
echo "   • Click 'Create Web Service'"
echo ""

echo "4️⃣  Deploy Frontend to Vercel:"
echo "   • Go to https://vercel.com"
echo "   • Click 'New Project'"
echo "   • Import your GitHub repository"
echo "   • Framework Preset: Vite"
echo "   • Root Directory: frontend"
echo "   • Build Command: npm run build"
echo "   • Output Directory: dist"
echo "   • Install Command: npm ci"
echo "   • Environment Variables (add these in Vercel dashboard):"
echo "     - VITE_API_BASE_URL: https://YOUR_RENDER_SERVICE_URL"
echo "     - VITE_JUPITER_REFERRAL_ACCOUNT: 42DqmQMZrVeZkP2Btj2cS96Ej81jVxFqwUZWazVvhUPt"
echo "     - VITE_JUPITER_REFERRAL_FEE_BPS: 70"
echo "   • Click 'Deploy'"
echo ""

echo "5️⃣  Update Frontend API URL:"
echo "   • After Render deployment, copy your backend URL"
echo "   • Go to Vercel dashboard → your project → Settings → Environment Variables"
echo "   • Update VITE_API_BASE_URL with your Render URL"
echo "   • Redeploy frontend"
echo ""

echo "🎉 Deployment Complete!"
echo "Your app should be live at:"
echo "• Frontend: https://your-app.vercel.app"
echo "• Backend: https://your-app.onrender.com"
echo ""

echo "🔄 Auto-deployment:"
echo "Both services will automatically redeploy when you push to the main branch."
