#!/bin/bash

echo "🚀 MoonFeed Deployment Guide"
echo "=============================="
echo ""

echo "📋 Prerequisites:"
echo "1. GitHub account"
echo "2. Vercel account (connected to GitHub)"
echo "3. Render account"
echo ""

echo "🔧 Initial Setup (One-time):"
echo ""

echo "1️⃣  Create GitHub Repository:"
echo "   • Go to https://github.com/new"
echo "   • Repository name: moonfeed"
echo "   • Make it public (or private if you prefer)"
echo "   • Don't initialize with README (we already have one)"
echo "   • Click 'Create repository'"
echo ""

echo "2️⃣  Push to GitHub:"
echo "   Run these commands in your terminal:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/moonfeed.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo "3️⃣  Deploy Backend to Render:"
echo "   • Go to https://render.com"
echo "   • Click 'New' → 'Web Service'"
echo "   • Connect your GitHub repository"
echo "   • Select your moonfeed repository"
echo "   • Name: moonfeed-backend"
echo "   • Environment: Node"
echo "   • Build Command: npm install"
echo "   • Start Command: npm start"
echo "   • Root Directory: backend"
echo "   • Plan: Free"
echo "   • ⚠️  IMPORTANT: Disable 'Auto-Deploy' in settings"
echo "   • Click 'Create Web Service'"
echo ""

echo "4️⃣  Deploy Frontend to Vercel:"
echo "   • Go to https://vercel.com"
echo "   • Click 'New Project'"
echo "   • Import your GitHub repository"
echo "   • Framework Preset: Vite"
echo "   • Root Directory: frontend"
echo "   • Build Command: npm run build"
echo "   • Output Directory: dist"
echo "   • Install Command: npm ci"
echo "   • ⚠️  IMPORTANT: In project settings, disable 'Git Integration' auto-deploy"
echo "   • Environment Variables (add these in Vercel dashboard):"
echo "     - VITE_API_BASE_URL: https://YOUR_RENDER_SERVICE_URL"
echo "     - VITE_JUPITER_REFERRAL_ACCOUNT: 42DqmQMZrVeZkP2Btj2cS96Ej81jVxFqwUZWazVvhUPt"
echo "     - VITE_JUPITER_REFERRAL_FEE_BPS: 70"
echo "   • Click 'Deploy'"
echo ""

echo "🔄 Manual Deployment Workflow:"
echo ""
echo "For each update:"
echo "1. Run: ./test-before-deploy.sh (test locally)"
echo "2. Push changes: git add . && git commit -m 'your message' && git push"
echo "3. Run: ./deploy-manual.sh (deploy when ready)"
echo ""

echo "🎉 Setup Complete!"
echo "Your app will be live at:"
echo "• Frontend: https://your-app.vercel.app"
echo "• Backend: https://your-app.onrender.com"
echo ""

echo "✨ Benefits of Manual Deployment:"
echo "• Full control over when updates go live"
echo "• Test locally before deploying"
echo "• Deploy backend and frontend separately"
echo "• No surprise deployments from accidental commits"
echo ""

echo "📝 Available Scripts:"
echo "• ./test-before-deploy.sh - Test before deploying"
echo "• ./deploy-manual.sh - Manual deployment controller"
echo "• ./deploy.sh - This setup guide"
