#!/bin/bash
# Quick Fix Guide: Top Traders API Key Configuration

echo "═══════════════════════════════════════════════════════════════"
echo "🔧 MOONFEED - TOP TRADERS API KEY FIX GUIDE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📋 ISSUE: Top Traders button returns 401 (Invalid API key)"
echo ""
echo "🎯 SOLUTION STEPS:"
echo ""
echo "1️⃣  GET API KEY"
echo "   → Visit: https://solanatracker.io"
echo "   → Sign up or log in"
echo "   → Navigate to API/Developer section"
echo "   → Copy your API key"
echo ""
echo "2️⃣  CONFIGURE ON RENDER"
echo "   → Go to: https://dashboard.render.com"
echo "   → Select your backend service (moonfeed-backend)"
echo "   → Click 'Environment' tab"
echo "   → Add/Update variable:"
echo "      Name:  SOLANA_TRACKER_API_KEY"
echo "      Value: [paste your API key]"
echo "   → Click 'Save Changes'"
echo ""
echo "3️⃣  VERIFY DEPLOYMENT"
echo "   → Render will auto-redeploy (takes 2-3 minutes)"
echo "   → Or click 'Manual Deploy' > 'Deploy latest commit'"
echo "   → Wait for 'Live' status"
echo ""
echo "4️⃣  TEST THE FIX"
echo "   → Run this script again to test:"
echo "      curl \"https://api.moonfeed.app/api/top-traders/HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC\""
echo ""
echo "   → Expected response:"
echo "      {\"success\":true,\"data\":[...],\"count\":10}"
echo ""
echo "5️⃣  TEST ON MOBILE"
echo "   → Open https://moonfeed.app on mobile"
echo "   → Tap any coin card"
echo "   → Tap 'Top Traders' button"
echo "   → Should see list of traders with PnL data"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🧪 Testing current endpoint status..."
echo ""

# Test the endpoint
response=$(curl -s "https://api.moonfeed.app/api/top-traders/HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC")

if echo "$response" | grep -q "\"success\":true"; then
    echo "✅ SUCCESS! Top Traders API is working!"
    echo "$response" | python3 -m json.tool 2>/dev/null || echo "$response"
else
    echo "❌ STILL BROKEN - API key not configured yet"
    echo "$response" | python3 -m json.tool 2>/dev/null || echo "$response"
    echo ""
    echo "👉 Follow the steps above to configure the API key"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📖 Full documentation: TOP_TRADERS_API_KEY_ISSUE.md"
echo "═══════════════════════════════════════════════════════════════"
