#!/bin/bash

echo "🗄️  MongoDB Atlas Setup Guide for MoonFeed"
echo "=========================================="
echo ""
echo "Follow these steps to set up MongoDB Atlas (Cloud Database - FREE)"
echo ""

echo "📋 STEP 1: Create MongoDB Atlas Account"
echo "  1. Go to: https://www.mongodb.com/cloud/atlas"
echo "  2. Click 'Try Free' and sign up"
echo ""

echo "📋 STEP 2: Create Free Cluster"
echo "  1. Choose 'M0 FREE' tier (no credit card needed)"
echo "  2. Select AWS and a region close to you"
echo "  3. Name it 'moonfeed-cluster' (or any name)"
echo "  4. Click 'Create Cluster' (takes 3-5 min)"
echo ""

echo "📋 STEP 3: Create Database User"
echo "  1. Click 'Database Access' in left sidebar"
echo "  2. Click 'Add New Database User'"
echo "  3. Username: moonfeed-admin"
echo "  4. Click 'Autogenerate Secure Password'"
echo "  5. ⚠️  COPY AND SAVE THE PASSWORD!"
echo "  6. Privileges: 'Read and write to any database'"
echo "  7. Click 'Add User'"
echo ""

echo "📋 STEP 4: Allow Network Access"
echo "  1. Click 'Network Access' in left sidebar"
echo "  2. Click 'Add IP Address'"
echo "  3. Click 'Allow Access from Anywhere' (0.0.0.0/0)"
echo "  4. Click 'Confirm'"
echo ""

echo "📋 STEP 5: Get Connection String"
echo "  1. Click 'Database' in left sidebar"
echo "  2. Click 'Connect' button on your cluster"
echo "  3. Choose 'Connect your application'"
echo "  4. Copy the connection string"
echo "  5. It looks like:"
echo "     mongodb+srv://moonfeed-admin:<password>@cluster0.xxxxx.mongodb.net/?retryWrites=true&w=majority"
echo ""

echo "📋 STEP 6: Update Your .env File"
echo "  1. Replace <password> with your actual password"
echo "  2. Add '/moonfeed' after '.net' and before '?'"
echo "  3. Final format:"
echo "     mongodb+srv://moonfeed-admin:YOUR_PASSWORD@cluster0.xxxxx.mongodb.net/moonfeed?retryWrites=true&w=majority"
echo ""

echo "⏳ When you have your connection string, run:"
echo "   ./configure-mongodb.sh"
echo ""
echo "=========================================="
